// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAasaWRjkxUPhlnqiK-lb3t1LVSil8P5Ko',
    appId: '1:437893918475:web:356cbf5abe9a54dfd6bc0e',
    messagingSenderId: '437893918475',
    projectId: 'sareer-publications-80391',
    authDomain: 'sareer-publications-80391.firebaseapp.com',
    databaseURL: 'https://sareer-publications-80391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sareer-publications-80391.firebasestorage.app',
    measurementId: 'G-W7P1FNG8VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCpJQli92DlKu6oib8h__CB_p_2BRU_U',
    appId: '1:437893918475:android:2557bd1428a4113ad6bc0e',
    messagingSenderId: '437893918475',
    projectId: 'sareer-publications-80391',
    databaseURL: 'https://sareer-publications-80391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sareer-publications-80391.firebasestorage.app',
  );
}
